name: Ben Brewster
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
collections:
  projects:
    output: true
    permalink: /projects/:path/
  videos:
    output: true
    permalink: /videos/:path/
  podcasts:
    output: true
    permalink: /podcasts/:path/
